# Generated by Django 6.1.1 on 2026-09-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_remove_user_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('client', 'Клиент'), ('shop', 'Поставщик')], default='client', max_length=10),
        ),
    ]
